import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timedelta, timezone

from database.db import db
from database.models import Alert, Detection

logger = logging.getLogger(__name__)

SEVERITY_COLORS = {
    'critical': '#D50000',
    'high': '#FF6D00',
    'medium': '#FFD600',
    'low': '#00C853',
}


class AlertService:
    """Handles creating, sending, and managing garbage-detection alerts."""

    def __init__(self, app=None):
        self.app = app

    def init_app(self, app):
        self.app = app

    # ------------------------------------------------------------------ #
    # Public
    # ------------------------------------------------------------------ #

    def send_alert(self, detection: Detection, alert_type: str = 'system') -> Alert:
        """Create an alert record and attempt to dispatch it."""
        if not self._should_send_alert(detection.location_name):
            logger.info("Alert cooldown active for %s — skipping.", detection.location_name)
            return None

        alert = self._create_system_alert(detection)

        if alert_type == 'email':
            self._send_email_alert(detection, alert)

        detection.alert_sent = True
        db.session.commit()
        return alert

    # ------------------------------------------------------------------ #
    # Internal helpers
    # ------------------------------------------------------------------ #

    def _create_system_alert(self, detection: Detection) -> Alert:
        message = self.get_alert_message(detection)
        alert = Alert(
            detection_id=detection.id,
            alert_type='system',
            severity=detection.severity,
            message=message,
            location_name=detection.location_name,
            status='pending',
        )
        db.session.add(alert)
        db.session.commit()
        return alert

    def _send_email_alert(self, detection: Detection, alert: Alert):
        """Attempt to send an HTML email alert (best-effort)."""
        try:
            app = self.app
            if app is None:
                logger.warning("No Flask app context — cannot read email config.")
                return

            from_addr = app.config.get('ALERT_EMAIL_FROM', '')
            password = app.config.get('ALERT_EMAIL_PASSWORD', '')
            to_addr = app.config.get('ALERT_EMAIL_TO', '')
            smtp_server = app.config.get('SMTP_SERVER', 'smtp.gmail.com')
            smtp_port = app.config.get('SMTP_PORT', 587)

            if not all([from_addr, password, to_addr]):
                logger.info("Email config incomplete — skipping email alert.")
                alert.alert_type = 'system'
                db.session.commit()
                return

            severity_upper = detection.severity.upper()
            color = SEVERITY_COLORS.get(detection.severity, '#999')
            subject = f"[{severity_upper}] GreenCity Alert — {detection.location_name}"

            html_body = f"""
            <html><body style="font-family:Arial,sans-serif;background:#0A0E1A;color:#F9FAFB;padding:20px;">
              <div style="max-width:600px;margin:auto;background:#111827;border-radius:12px;padding:24px;border-left:4px solid {color};">
                <h2 style="color:{color};margin-top:0;">🚨 {severity_upper} ALERT</h2>
                <p><strong>Location:</strong> {detection.location_name or 'Unknown'}</p>
                <p><strong>Severity:</strong>
                  <span style="background:{color};color:#fff;padding:2px 10px;border-radius:8px;">{severity_upper}</span>
                </p>
                <p><strong>Detections:</strong> {detection.detection_count} item(s)</p>
                <p><strong>Bin fill level:</strong> {detection.bin_fill_level}</p>
                <p><strong>Time:</strong> {detection.timestamp.strftime('%Y-%m-%d %H:%M:%S') if detection.timestamp else 'N/A'}</p>
                <hr style="border-color:#333;">
                <p style="color:#9CA3AF;font-size:13px;">This alert was generated by the GreenCity Waste Intelligence System.</p>
              </div>
            </body></html>
            """

            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From'] = from_addr
            msg['To'] = to_addr
            msg.attach(MIMEText(html_body, 'html'))

            with smtplib.SMTP(smtp_server, smtp_port, timeout=10) as server:
                server.starttls()
                server.login(from_addr, password)
                server.sendmail(from_addr, to_addr, msg.as_string())

            alert.status = 'sent'
            alert.alert_type = 'email'
            db.session.commit()
            logger.info("Email alert sent for detection %s", detection.id)
        except Exception as exc:
            logger.error("Email alert failed: %s", exc)
            alert.alert_type = 'system'
            db.session.commit()

    @staticmethod
    def get_alert_message(detection: Detection) -> str:
        severity = detection.severity.upper()
        location = detection.location_name or 'Unknown location'
        count = detection.detection_count or 0
        classes = detection.get_detected_classes()
        class_str = ', '.join(c.replace('_', ' ') for c in classes) if classes else 'waste items'

        if severity == 'CRITICAL':
            return (
                f"CRITICAL: Garbage overflow detected at {location} — "
                f"{count} waste items found ({class_str}). Immediate cleanup required."
            )
        if severity == 'HIGH':
            return (
                f"HIGH: Significant waste accumulation at {location} — "
                f"{count} items detected ({class_str}). Cleanup recommended promptly."
            )
        if severity == 'MEDIUM':
            return (
                f"MEDIUM: Moderate waste detected at {location} — "
                f"{count} items ({class_str}). Schedule routine cleanup."
            )
        return (
            f"LOW: Minor waste spotted at {location} — "
            f"{count} items ({class_str}). No immediate action needed."
        )

    def _should_send_alert(self, location_name: str) -> bool:
        """Return False if an alert was already sent for this location within the cooldown window."""
        if not location_name:
            return True
        cooldown = 30
        if self.app:
            cooldown = self.app.config.get('ALERT_COOLDOWN_MINUTES', 30)
        cutoff = datetime.now(timezone.utc) - timedelta(minutes=cooldown)
        recent = Alert.query.filter(
            Alert.location_name == location_name,
            Alert.created_at >= cutoff,
        ).first()
        return recent is None
